site_name: EmailBot for Discord
repo_url: https://github.com/lkaesberg/EmailBot
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: https://raw.githubusercontent.com/lkaesberg/EmailBot/main/images/emailbot-border.png
  favicon: https://raw.githubusercontent.com/lkaesberg/EmailBot/main/images/emailbot.png
  palette:
    scheme: default
    primary: black
    accent: yellow
  features:
    - navigation.tabs
nav:
  - 'index.md'
  - 'commands.md'
  - 'contributing.md'
  - 'legal.md'
  - Fund the Project: https://www.paypal.com/donate/?hosted_button_id=22PJP92QSLB2J
