site_name: EmailBot
theme:
  name: material
  logo: images/emailbot.png
  favicon: images/emailbot.png
  palette:
    scheme: slate
    primary: black
    accent: yellow
  features:
    - navigation.tabs
nav:
  - 'index.md'
