site_name: EmailBot
theme:
  name: material
  logo: https://raw.githubusercontent.com/lkaesberg/EmailBot/main/images/emailbot.png
  favicon: https://raw.githubusercontent.com/lkaesberg/EmailBot/main/images/emailbot.png
  palette:
    scheme: slate
    primary: blue
    accent: white
  features:
    - navigation.tabs
nav:
  - 'index.md'
  - 'commands.md'
  - 'contributing.md'
