site_name: EmailBot
repo_url: https://github.com/lkaesberg/EmailBot
theme:
  name: material
  logo: https://raw.githubusercontent.com/lkaesberg/EmailBot/main/images/emailbot-border.png
  favicon: https://raw.githubusercontent.com/lkaesberg/EmailBot/main/images/emailbot.png
  palette:
    scheme: default
    primary: black
    accent: yellow
  features:
    - navigation.tabs
nav:
  - 'index.md'
  - 'commands.md'
  - 'contributing.md'
